# Generated by Django 4.2.4 on 2023-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AS', 'Adulto sin identificación'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cedula de Extranjería'), ('CD', 'Carnet diplomático'), ('CN', 'Certificado Nacido Vivo'), ('MS', 'Menor sin Identificación'), ('NU', 'No. Único de Id. Personal'), ('PA', 'Pasaporte'), ('PE', 'Per Especial Permanencia'), ('PT', 'Permiso por Protección Temporal'), ('RC', 'Registro Civil'), ('SC', 'Salvo Conducto'), ('TI', 'Tarjeta de Identidad')], max_length=2, null=True)),
                ('identification_number', models.PositiveIntegerField(null=True, unique=True)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('eps', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('second_last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True, unique=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('affiliation_state', models.CharField(choices=[('activo', 'activo'), ('retirado', 'retirado')], max_length=10, null=True)),
                ('membership_type', models.CharField(choices=[('cotizante', 'cotizante')], max_length=10, null=True)),
                ('eps_user', models.CharField(max_length=255, null=True)),
                ('password_eps', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
